language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch

# command to install dependencies
install:
  - pip install .[test]
# command to run tests
script:
  - make verifypep8 test
